-- ================================================================
-- 看板流水线 · 快照仓表结构（只要表样，无数据）
-- 源: data_warehouse\YYYYMM\erp_snapshot.parquet（ERP 月度明文快照）
-- 导出: 2026-08-28 | 通用 SQL 写法（SQL Server/MySQL/SQLite 微调即可）
-- 说明: 快照仓每月一期（YYYYMM 目录），表结构即 ERP 导出 Excel 的落库形态
-- ================================================================

-- 源文件: erp_snapshot.parquet  (行数: 191725)
CREATE TABLE [erp_snapshot] (
    [发货日期] DATETIME NULL,
    [快递单号] VARCHAR(255) NULL,
    [客户订单号] VARCHAR(255) NULL,
    [销售部门] VARCHAR(255) NULL,
    [实际业务员] VARCHAR(255) NULL,
    [代理商/直供名称] VARCHAR(255) NULL,
    [实际终端客户] VARCHAR(255) NULL,
    [终端客户简称] VARCHAR(255) NULL,
    [助理备注] VARCHAR(255) NULL,
    [存货名称] VARCHAR(255) NULL,
    [发货数量] BIGINT NULL,
    [原币含税单价] DOUBLE NULL,
    [出货总金额] DOUBLE NULL,
    [单位成本] DOUBLE NULL,
    [总成本] DOUBLE NULL,
    [RMB 未税金额小计] DOUBLE NULL,
    [利润] DOUBLE NULL,
    [丝印] VARCHAR(255) NULL,
    [批号] VARCHAR(255) NULL,
    [币种] VARCHAR(255) NULL,
    [汇率] DOUBLE NULL,
    [细分市场（新）] VARCHAR(255) NULL,
    [细分市场] VARCHAR(255) NULL,
    [产品线] VARCHAR(255) NULL,
    [型号_产品线（新）] VARCHAR(255) NULL,
    [产品系列] VARCHAR(255) NULL,
    [型号_产品品类] VARCHAR(255) NULL,
    [产品类别] VARCHAR(255) NULL,
    [是否新品] VARCHAR(255) NULL,
    [型号_产品结构名称] VARCHAR(255) NULL,
    [CRM销售] VARCHAR(255) NULL,
    [ERP业务员姓名] VARCHAR(255) NULL,
    [ERP所属公司] VARCHAR(255) NULL,
    [ERP订单号] VARCHAR(255) NULL,
    [发货单号] VARCHAR(255) NULL,
    [未税单价] DOUBLE NULL,
    [客户] VARCHAR(255) NULL,
    [终端名称] VARCHAR(255) NULL,
    [发货地址] VARCHAR(255) NULL,
    [客户存货编码] VARCHAR(255) NULL,
    [表头备注] VARCHAR(255) NULL,
    [月结条件] VARCHAR(255) NULL,
    [lot] VARCHAR(255) NULL,
    [版本] VARCHAR(255) NULL,
    [档位] VARCHAR(255) NULL,
    [行号] DOUBLE NULL,
    [PM] VARCHAR(255) NULL,
    [销售订单子表主键标识] VARCHAR(255) NULL,
    [业务类型] VARCHAR(255) NULL,
    [销售类型编码] BIGINT NULL,
    [销售类型名称] VARCHAR(255) NULL,
    [销售助理] VARCHAR(255) NULL,
    [发运方式编码] DOUBLE NULL,
    [发运方式名称] VARCHAR(255) NULL,
    [利润中心] VARCHAR(255) NULL,
    [发货退货单子表标识] VARCHAR(255) NULL,
    [业务员对应工号] VARCHAR(255) NULL,
    [存货编码] BIGINT NULL,
    [制单人] VARCHAR(255) NULL,
    [型号] BIGINT NULL,
    [终端客户名称] VARCHAR(255) NULL,
    [关联订单明细] DOUBLE NULL,
    [原币税额] DOUBLE NULL,
    [终端客户名称_客户类别] VARCHAR(255) NULL,
    [代理商系统账号] VARCHAR(255) NULL,
    [销售模式] VARCHAR(255) NULL,
    [产品品类（新）] VARCHAR(255) NULL
);
